### PR TITLE
Fix publish-snapshot.sh script to only push artifacts ending with -SNAPSHOT

### LINKED ISSUE #439: publish-snapshot script is publishing the first jar it finds next to a pom.
We have Snapshot publications that are including extra jars.  These jars are incorrectly being picked up by the [publish-snapshot.sh](https://github.com/opensearch-project/opensearch-build/blob/main/publish/publish-snapshot.sh#L114) script and published with mvn deploy-file.  As a result it is pushed to Sonatype as the latest publication, but is not the correct jar.

For example
`org/opensearch/gradle/build-tools/1.1.0-SNAPSHOT/` publishes two jars:
`build-tools-1.1.0-SNAPSHOT-test-fixtures.jar` and `build-tools-1.1.0-SNAPSHOT.jar`

The script is picking up `build-tools-1.1.0-SNAPSHOT-test-fixtures.jar` and pushing under sonatype as:
`
/org/opensearch/gradle/build-tools/1.1.0-SNAPSHOT/build-tools-1.1.0-20210910.002130-165.jar`

When the dependency is used, the incorrect jar is fetched.  Specifically for plugins & build-tools, this results in the following error.

```
* Where:
Build file '/Users/handalm/workspace/job-scheduler/build.gradle' line: 48

* What went wrong:
A problem occurred evaluating root project 'opensearch-job-scheduler'.
> Plugin with id 'opensearch.opensearchplugin' not found.
```
Note - this is *NOT* an issue for release builds that are pushed with the stage-maven-release.sh script.  That script using a separate nexus staging plugin that pushes all artifacts that are in the folder.  Unfortunately we cannot use that to push snapshots.

### PR DESCRIPTION
**Pull request by mch2**
Fix publish-snapshot.sh script to only push artifacts ending with -SNAPSHOT.jar|war|zip.

Signed-off-by: Marc Handalian <handalm@amazon.com>

### Description
This change ensures we are not pushing incorrect artifacts with the deploy:deploy-file plugin.
All publications will name the real artifact that needs to be published end with -SNAPSHOT.<extension>.

Removed line explicitly checking for sources/javadoc jars.  These will be skipped bc they do not end in `-SNAPSHOT.<extension>`
 
Tested this with a local run that skips the mvn publish command to ensure we attempt to push the correct files.

```
~/workspace/opensearch-build (main)$ ./publish/publish-snapshot.sh test
searching for poms under /Users/handalm/workspace/opensearch-build/test
Skipping upload for additional artifact: ./1.1.0-SNAPSHOT/build-tools-1.1.0-SNAPSHOT-javadoc.jar
Skipping upload for additional artifact: ./1.1.0-SNAPSHOT/build-tools-1.1.0-SNAPSHOT-sources.jar
Skipping upload for additional artifact: ./1.1.0-SNAPSHOT/build-tools-1.1.0-SNAPSHOT-test-fixtures.jar
Uploading: ./1.1.0-SNAPSHOT/build-tools-1.1.0-SNAPSHOT.jar with ./1.1.0-SNAPSHOT/build-tools-1.1.0-SNAPSHOT.pom to https://aws.oss.sonatype.org/content/repositories/snapshots/
Skipping upload for ./1.1.0-SNAPSHOT/build-tools-1.1.0-SNAPSHOT.module
Skipping upload for ./1.1.0-SNAPSHOT/maven-metadata-local.xml
Finished uploading ./1.1.0-SNAPSHOT
===========================================
Done.
===========================================

```

### Issues Resolved
#439 
 
### Check List
- [ x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: publish/publish-snapshot.sh [hunk 1]
```diff
@@ -47,20 +47,20 @@ while getopts ":h" option; do
...
+#
+#[ -z "${SONATYPE_PASSWORD}" ] && {
+#  echo "SONATYPE_PASSWORD is required"
+#  exit 1
+#}
+#
+#[ -z "${SNAPSHOT_REPO_URL}" ] && {
+#  echo "REPO_URL is required"
+#  exit 1
+#}
```
Comment (dblock) [inline publish/publish-snapshot.sh:63]: Qu'est-ce que c'est?

**Review by dblock — CHANGES_REQUESTED** [review]

File: publish/publish-snapshot.sh (hunk 1 above)
Comment (mch2) [reply publish/publish-snapshot.sh:63]: oof

Comment (mch2) [reply publish/publish-snapshot.sh]: fixed - <facepalm>

**Review by dblock — APPROVED** [review]
YOLO

File: publish/publish-snapshot.sh [hunk 2]
```diff
@@ -111,20 +111,26 @@ fi
 for pom in ${pomFiles}; do
   pom_dir="$(dirname "${pom}")"
   for FILE in "${pom_dir}"/*;  do
-    if [[ ! $FILE == *"-javadoc.jar"* ]] && [[ ! $FILE == *"-sources.jar"* ]]; then
+    if [[ $FILE == $pom ]] ; then
+      continue
+    fi
```
Comment (peterzhuamazon) [inline publish/publish-snapshot.sh:116]: This might be nitpick but isnt if file != $pom is better logic?
Or the small if loop is prefered here?

File: publish/publish-snapshot.sh [hunk 3]
```diff
@@ -111,20 +111,26 @@ fi
...
-        echo "Uploading: ${FILE} to ${url}"
+        # Ensure we are only pushing the artifact that ends with -SNAPSHOT.<extension> and its pom.
+        if [[ $FILE == *SNAPSHOT.${extension} ]] ; then
+         echo "Uploading: ${FILE} with ${pom} to ${url}"
          mvn --settings="${mvn_settings}" deploy:deploy-file \
          -DgeneratePom=false \
          -DrepositoryId=nexus \
          -Durl="${SNAPSHOT_REPO_URL}" \
          -DpomFile="${pom}" \
          -Dfile="${FILE}" || echo "Failed to upload ${FILE}"
```
Comment (peterzhuamazon) [inline publish/publish-snapshot.sh:127]: Nitpick, spacing needs some improvements right here.

Comment (mch2) [reply publish/publish-snapshot.sh]: Updated - ran shfmt on the file.

File: publish/publish-snapshot.sh (hunk 2 above)
Comment (mch2) [reply publish/publish-snapshot.sh]: Updated and added a comment why this is skipped.

**Review by dblock — APPROVED** [review]

**Review by peterzhuamazon — APPROVED** [review]
