### PR TITLE
Include chromium binary in dashboards-reports artifact

### LINKED ISSUE #934: [Bug]: Reporting build missing chromium dependency
### Describe the bug

dashboards-reports plugin uses chromium to generate reports, the binary should be included in the artifact like this:
https://github.com/opensearch-project/dashboards-reports/blob/main/.github/workflows/dashboards-reports-test-and-build-workflow.yml#L67-L91

But this part is missing in [build.sh](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/reportsDashboards/build.sh#L64-L77).

### To reproduce

Run opensearch and dashboards, reporting does not work because chromium binary `reportsDashboards/.chromium/headless_shell` does not exist

### PR DESCRIPTION
**Pull request by joshuali925**
Signed-off-by: Joshua Li <joshuali925@gmail.com>

### Description
Include chromium binary in dashboards-reports artifact, binaries are from https://github.com/opensearch-project/dashboards-reports/releases/tag/chromium-1.12.0.0 ([docs](https://github.com/opensearch-project/dashboards-reports/tree/main/dashboards-reports/rendering-engine/headless-chrome))

Limit dashboards-reports dashboards plugin to linux platform only, darwin-arm64 and windows-arm64 chromium binaries are not available yet.
 
### Issues Resolved
#934 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: scripts/components/reportsDashboards/build.sh [hunk 1]
```diff
@@ -72,6 +97,12 @@ echo "BUILD MODULES FOR $PLUGIN_NAME"
...
+mkdir -p ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER/build/opensearch-dashboards/$PLUGIN_NAME
+curl -sLO "$CHROMIUM_URL"
+echo "PUTTING CHROMIUM INSIDE $PLUGIN_NAME-$VERSION.zip"
+unzip "$CHROMIUM_TARGET" -d ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER/build/opensearch-dashboards/$PLUGIN_NAME
+(cd ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER/build && zip -ur $PLUGIN_NAME-$VERSION.zip opensearch-dashboards)
 echo "COPY $PLUGIN_NAME.zip"
 cp -r ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER/build/$PLUGIN_NAME-$VERSION.zip $OUTPUT/plugins/
-rm -rf ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER
\ No newline at end of file
+rm -rf ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER
```
Comment (kavilla) [inline scripts/components/reportsDashboards/build.sh:108]: Wonder why git is saying a change is here

File: scripts/components/reportsDashboards/build.sh [hunk 2]
```diff
@@ -72,6 +97,12 @@ echo "BUILD MODULES FOR $PLUGIN_NAME"
 (cd ../../OpenSearch-Dashboards && yarn osd bootstrap)
 echo "BUILD RELEASE ZIP FOR $PLUGIN_NAME"
 (cd ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER && yarn plugin_helpers build)
+echo "DOWNLOADING CHROMIUM FOR $PLUGIN_NAME"
```
Comment (kavilla) [inline scripts/components/reportsDashboards/build.sh:100]: can we have a mention here why we have to do this. i know why but like in code comment.

**Review by kavilla — APPROVED** [review]
Verified with `wget -c https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/369/linux/x64/dist/opensearch-dashboards-1.2.0-linux-x64.tar.gz  -O - | tar -xz`

navigating to Reporting plugin to downloading reports works

File: scripts/components/reportsDashboards/build.sh [hunk 3]
```diff
@@ -61,6 +61,31 @@ fi
...
+    x64|arm64)
+        CHROMIUM_TARGET="chromium-$PLATFORM-$ARCHITECTURE.zip"
+        ;;
+    *)
+        echo "Unsupported architecture: $ARCHITECTURE"
+        exit 1
+        ;;
+esac
+
+CHROMIUM_URL="https://github.com/opensearch-project/dashboards-reports/releases/download/chromium-1.12.0.0/$CHROMIUM_TARGET"
```
Comment (peterzhuamazon) [inline scripts/components/reportsDashboards/build.sh:87]: 1.12.0 should be passed from $VERSION.

File: scripts/components/reportsDashboards/build.sh (hunk 1 above)
Comment (dblock) [reply scripts/components/reportsDashboards/build.sh:108]: CR/LF

**Review by dblock — APPROVED** [review]

File: scripts/components/reportsDashboards/build.sh (hunk 3 above)
Comment (joshuali925) [reply scripts/components/reportsDashboards/build.sh:87]: this `chromium-1.12.0.0` is a fixed tag we used to put compiled chromium binaries. we won't release new chromiums in every opensearch release

File: scripts/components/reportsDashboards/build.sh (hunk 2 above)
Comment (joshuali925) [reply scripts/components/reportsDashboards/build.sh:100]: sure

File: scripts/components/reportsDashboards/build.sh (hunk 3 above)
Comment (gaiksaya) [reply scripts/components/reportsDashboards/build.sh:87]: I think this is static endpoint. https://github.com/opensearch-project/dashboards-reports/releases/tag/chromium-1.12.0.0
Not something that is generated per version

File: scripts/components/reportsDashboards/build.sh (hunk 1 above)
Comment (joshuali925) [reply scripts/components/reportsDashboards/build.sh:108]: my editor adds a new line to the end of file automatically..

File: scripts/components/reportsDashboards/build.sh (hunk 3 above)
Comment (kavilla) [reply scripts/components/reportsDashboards/build.sh:87]: Version would be like OpenSearch Dashboards plugin version.

**Comment by kavilla** [comment]
@gaiksaya @peterzhuamazon any objections to me merging this in as is?

**Comment by gaiksaya** [comment]
> @gaiksaya @peterzhuamazon any objections to me merging this in as is?

Nope 🚢 it!

**Comment by peterzhuamazon** [comment]
> @gaiksaya @peterzhuamazon any objections to me merging this in as is?

I have, please see my last comment about zip/unzip.

**Comment by kavilla** [comment]
> I have, please see my last comment about zip/unzip.

Which one, not seeing one about zip/unzip

**Comment by peternied** [comment]
> > @gaiksaya @peterzhuamazon any objections to me merging this in as is?
> 
> I have, please see my last comment about zip/unzip.

@peterzhuamazon I don't see your comment either, is this blocking or can this change be merged?

**Comment by peternied** [comment]
I am merging @peterzhuamazon please create another issue if we need follow up

File: scripts/components/reportsDashboards/build.sh [hunk 4]
```diff
@@ -72,6 +97,12 @@ echo "BUILD MODULES FOR $PLUGIN_NAME"
 (cd ../../OpenSearch-Dashboards && yarn osd bootstrap)
 echo "BUILD RELEASE ZIP FOR $PLUGIN_NAME"
 (cd ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER && yarn plugin_helpers build)
+echo "DOWNLOADING CHROMIUM FOR $PLUGIN_NAME"
+mkdir -p ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER/build/opensearch-dashboards/$PLUGIN_NAME
+curl -sLO "$CHROMIUM_URL"
+echo "PUTTING CHROMIUM INSIDE $PLUGIN_NAME-$VERSION.zip"
+unzip "$CHROMIUM_TARGET" -d ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER/build/opensearch-dashboards/$PLUGIN_NAME
+(cd ../../OpenSearch-Dashboards/plugins/$PLUGIN_FOLDER/build && zip -ur $PLUGIN_NAME-$VERSION.zip opensearch-dashboards)
```
[the remark this answers is not in the document]
Comment (kavilla) [reply scripts/components/reportsDashboards/build.sh:105]: Gotcha, yeah I ran into through the pipeline. Seems to work for that not positive about the production of docker images.

[the remark this answers is not in the document]
Comment (peterzhuamazon) [reply scripts/components/reportsDashboards/build.sh:105]: If the pipeline succeed then yes the runner has zip/unzip.

Thanks.
