### PR TITLE
Permanent fix for OpenSearch and temp fix for Dashboards startup configurations

### LINKED ISSUE #1529: [BUG] OpenSearch v1.2.4 Docker image is broken while v1.2.3 just works
This command works
Captura de 2022-01-21 17-47-07

But this one doesn't

Captura de 2022-01-21 17-48-23

Errors are shown below

Captura de 2022-01-21 17-49-08
Captura de 2022-01-21 17-49-28
Captura de 2022-01-21 17-49-47
Captura de 2022-01-21 17-50-06

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Permanent fix for OpenSearch and temp fix for Dashboards startup configurations.

This PR utilize internal parsing of env var to permanently allow security plugin to be disabled, without the need of tweaking the config file on the fly for OpenSearch.

As for Dashboards, we still need to tweak the configuration file if we want to disable security plugin, so a new tweak is added to temporarily resolve the race condition introduced in #1130 #1458.

As for permanent fix for Dashboards I have opened an issue with Security Dashboards Plugin repo:
https://github.com/opensearch-project/security-dashboards-plugin/issues/896

Thanks.
 
### Issues Resolved
#1529 
#1567
https://github.com/opensearch-project/helm-charts/issues/198
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh [hunk 1]
```diff
@@ -160,8 +160,12 @@ function setupSecurityDashboardsPlugin {
         if [ "$DISABLE_SECURITY_DASHBOARDS_PLUGIN" = "true" ]; then
             echo "Disabling OpenSearch Security Dashboards Plugin"
             ./bin/opensearch-dashboards-plugin remove securityDashboards
-            cat $OPENSEARCH_DASHBOARDS_HOME/config/opensearch_dashboards.yml | sed "/^opensearch_security/d" | tee $OPENSEARCH_DASHBOARDS_HOME/config/opensearch_dashboards.yml
-            cat $OPENSEARCH_DASHBOARDS_HOME/config/opensearch_dashboards.yml | sed "s/https/http/g" | tee $OPENSEARCH_DASHBOARDS_HOME/config/opensearch_dashboards.yml
+
+            # Remove all security related parameters as well as changing HTTPS to HTTP
+            # Temporary fix before security-dashboards plugin implement a parameter to disable the plugin entirely
+            # https://github.com/opensearch-project/security-dashboards-plugin/issues/896
+            NEW_CONFIG=`cat $OPENSEARCH_DASHBOARDS_HOME/config/opensearch_dashboards.yml | sed "/^opensearch_security/d" | sed "s/https/http/g"`
```
Comment (peternied) [inline docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh:167]: Note, I am very paranoid about this change

How do we know that `var=cat | sed | sed` `echo $var > ` is any more / less reliable than what we did in the past?

Comment (dblock) [inline docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh:167]: UPDATED_CONFIG maybe?

**Review by dblock — APPROVED** [review]

File: docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh (hunk 1 above)
Comment (peterzhuamazon) [reply docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh:167]: It is more reliable because commands in a shell script are executed synchronously in sequence.

When you run something like this:
```
cmd1
cmd2
```

it is same as to run:
```
cmd1; cmd2
```

In previous iteration we are running cat/sed/tee in one single line/command, which cause the race condition to happen, as `tee` can set the file to empty before `cat` complete the reading of the file, since cat read in block size, thus cause the race condition to happen:
https://unix.stackexchange.com/questions/245499/how-does-cat-know-the-optimum-block-size-to-use

In new iteration, we allow cat and sed to complete processing of the entire file and save to the variable, before writing the content back to the file.

Since they are two different command, the 1st one will always complete, set the return code to 0, before the second command even start.

Thanks.

Comment (peterzhuamazon) [reply docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh]: Thanks, tweaked.

**Review by peternied — APPROVED** [review]

File: docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh (hunk 1 above)
Comment (peternied) [reply docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint.sh]: Thanks for the detailed explaination!
